name: Build TDLib for Android

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86, x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libssl-dev zlib1g-dev gperf

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: '26.1.10909125'
          add-to-path: true
          link-to-sdk: true

      - name: Cache NDK
        uses: actions/cache@v4
        with:
          path: ${{ env.ANDROID_HOME }}/ndk
          key: ${{ runner.os }}-ndk-${{ env.NDK_VERSION }}

      - name: Build TDLib for Android
        run: |
          mkdir build-${{ matrix.abi }}
          cd build-${{ matrix.abi }}
          cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=${{ matrix.abi }} \
                -DANDROID_PLATFORM=android-21 \
                -DANDROID_NDK=$ANDROID_NDK_HOME \
                -DTD_ENABLE_JNI=ON \
                -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
        env:
          ANDROID_NDK_HOME: ${{ env.ANDROID_HOME }}/ndk/${{ env.NDK_VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-android-${{ matrix.abi }}
          path: |
            build-${{ matrix.abi }}/
