name: Build TDLib for Android

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libssl-dev \
            zlib1g-dev \
            gperf \
            make \
            unzip \
            perl \
            wget \
            ninja-build \
            openjdk-17-jdk

      - name: Set up Java environment
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Clone TDLib
        run: |
          git clone --depth 1 https://github.com/tdlib/td.git td

      - name: Prepare Android toolchain
        run: |
          mkdir -p /home/runner/android
          cd /home/runner/android
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir -p cmdline-tools
          mv cmdline-tools cmdline-tools/latest
          export ANDROID_SDK_ROOT=$HOME/android
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "ndk;26.1.10909125" "platforms;android-21" "build-tools;34.0.0"

      - name: Build TDLib for armeabi-v7a
        run: |
          cd td
          mkdir -p build
          cd build
          cmake \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_SDK_ROOT/ndk/26.1.10909125/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../tdlib \
            ..
          cmake --build . --target install -j$(nproc)

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: tdlib-android-armeabi-v7a
          path: td/tdlib

