name: Build TDLib for Android

on: [push]

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [arm64-v8a, armeabi-v7a, x86, x86_64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libssl-dev zlib1g-dev gperf make unzip perl

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK and NDK
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.2.9519653" --sdk_root=$ANDROID_HOME
        env:
          ANDROID_HOME: /usr/local/lib/android/sdk

      - name: Cache NDK
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/android/sdk/ndk
          key: ${{ runner.os }}-ndk-25.2.9519653

      - name: Verify gperf
        run: |
          gperf --version
          which gperf

      - name: Build TDLib for Android
        run: |
          mkdir build-${{ matrix.abi }}
          cd build-${{ matrix.abi }}
          cmake -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
                -DANDROID_ABI=${{ matrix.abi }} \
                -DANDROID_PLATFORM=android-21 \
                -DANDROID_NDK=/usr/local/lib/android/sdk/ndk/25.2.9519653 \
                -DTD_ENABLE_JNI=ON \
                -DGPERF_EXECUTABLE=/usr/bin/gperf \
                -DCMAKE_BUILD_TYPE=Release ..
          make -j$(nproc)
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/25.2.9519653

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tdlib-android-${{ matrix.abi }}
          path: |
            build-${{ matrix.abi }}/
